### ISSUE TITLE
Support for specific families.

### ISSUE THREAD

**Issue by arq5x** [brentp/pedagree#1]
It would be nice to be able to do the following:

    from peddy import Ped, SEX, PHENOTYPE

    p = Ped('b.ped')

    # iterable
    f = p.families()

    # get a specific family by family_id
    shmoes = p.families('shmoes')

    # do neat stuff with a family.
    kids = shmoes.kids

    # it could get complictaed with multiple generations.  specify a generation
    granddad = shmoes.dad(generation=1)

**Comment by brentp** [comment]
can already do p.families['shmoes']

for the `family.dad` (shmoes.dad) what what if there are multiple grandparents or uncles?
